# Joint state controller (publish joint states)
joint_state_controller:
  publish_rate: 125
  type: joint_state_controller/JointStateController


#Position Controllers
joint1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_1
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_2
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_3
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_4
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_5
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint6_effort_controller:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_6
  pid: {p: 100.0, i: 0.01, d: 10.0}

joint7_effort_controller:
  type: effort_controllers/JointEffortController
  joint: iiwa_joint_7
  pid: {p: 100.0, i: 0.01, d: 10.0}